# Global
add_newline = true

format = """
$sudo$time$directory$git_branch$git_status$python$status$line_break$character
"""
scan_timeout = 50
command_timeout = 10000

[sudo]
format = "[ \uf0e7](bg:#eb6134 fg:#100e23)[](fg:#eb6134 bg:#5e03fc)"
disabled = false

[time]
disabled = false
format = "[$time ](bg:#5e03fc fg:#000000)[\ue0b0](fg:#5e03fc bg:#91ddff)"
time_format = "%Y-%m-%d %H:%M:%S"

[directory]
format = "[ $path](bg:#91ddff fg:#100e23)"
truncation_length = 0
truncate_to_repo = false
read_only = " 🔒"

[git_branch]
format = "[\ue0b0](fg:#91ddff bg:#275BF5)[ $branch](bg:#275BF5 fg:#ffffff)[\ue0b0](fg:#275BF5)"

[git_status]
style = "bold yellow"
ahead = "↑${count} "
behind = "↓${count} "
diverged = "↕${count} "
conflicted = "conflict:${count} "
deleted = "deleted:${count} "
renamed = "renamed:${count} "
modified = "modified:${count} "
staged = "staged:${count} "
untracked = "untracked:${count} "

[python]
format = "[ $virtualenv$version ](bg:#906cff fg:#100e23)[\ue0b0](fg:#906cff)"

[character]
success_symbol = "->"
error_symbol = "[->](bold red)"
