# Global
add_newline = true

format = """
$sudo$time$directory$git_branch$git_status$python$status$line_break$character
"""
scan_timeout = 50
command_timeout = 10000

[sudo]
format = "[ \uf0e7](bg:#eb6134 fg:#100e23)[](fg:#eb6134 bg:#5e03fc)"
disabled = false

[time]
disabled = false
format = "[$time ](bg:#5e03fc fg:#000000)"
time_format = "%Y-%m-%d %H:%M:%S"

[directory]
format = "[ $path](bg:#91ddff fg:#100e23)"
truncation_length = 0
truncate_to_repo = false
read_only = " 🔒"

[git_branch]
always_show_remote = true
format = "[ $symbol$branch(:$remote_branch)](bg:#275BF5 fg:#ffffff)"

[git_status]
ahead = "⬆️${count}"
behind = "⬇️${count}"
modified = "❗${count}"
staged = "☑️${count}"
untracked = "❓${count}"
deleted = "❌${count}"
conflicted = "↔️${count}"
diverged = "🔃${count}"
# up_to_date = "✅"

[python]
format = "[ $virtualenv$version ](bg:#906cff fg:#100e23)"

[character]
success_symbol = "➡️"
error_symbol = "[->](bold red)"
